load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
    name = "split_string_test",
    srcs = [
        "split_string_test.cc",
    ],
    deps = [
        "//dk_pull/common",
        "//third_party/gtest",
        "//third_party/gtest:gtest_main",
    ],
)
